FROM grafana/grafana
LABEL maintainer="Thibault <thibault.hulaux@gmail.com>" \
      description="grafana"

# # Update apt.
# RUN apt -y update

# # Install extra packets.
# RUN apt -y install bash vim

# # Clean up.
# RUN rm -rf /var/cache/apt/* && \
#     rm -rf /var/lib/apt/lists/* && \
#     apt-get clean

# Default run
# docker run -it --rm -p 8888:8080 tomcat:9.0

# Copy default web content
# COPY static-html-directory /usr/share/nginx/html

