version: '3.6'
# -------------------------------------------------------------------- networks
networks:
  swarm:
    name: 'swarm'
# --------------------------------------------------------------------- volumes
# volumes:
#   registry:
#     driver: "local"
#     driver_opts:
#       type: "nfs"
#       o: "addr=${MANAGER},nolock,soft,rw" # nolock and soft ensure docker doesn't freeze if the nfs connection is lost.
#       device: ":/data/${STACK}/registry"
# -------------------------------------------------------------------- services
services:
  registry:
    image: "registry:2"
    labels: [prometheus-job=registry]
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - swarm
    ports:
      - 5000:5000
    # volumes:
    #   - type: "volume"
    #     source: "registry"
    #     target: "/var/lib/registry"
    #     volume:
    #       nocopy: true