version: '3.7'

# networks:
#   python-net:
#     driver: overlay

# volumes:
#   prometheus:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "addr=thx-devops,nolock,soft,rw" # nolock and soft ensure docker doesn't freeze if the nfs connection is lost.
#       device: ":/data/monitoring/prometheus"

#   grafana:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "addr=thx-devops,nolock,soft,rw" # nolock and soft ensure docker doesn't freeze if the nfs connection is lost.
#       device: ":/data/monitoring/grafana"

services:
# ---------------------------------------------------------------------- python
  python:
    build:
      context: ${PYTHON_BUILD}
    container_name: ${PROJECT}-${PYTHON}
    restart: unless-stopped
    volumes:
      # - ${WEB_CONF}/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx conf (read-only)
      # - ${WEB_CONF}/conf.d:/etc/nginx/conf.d:ro # Nginx conf subsets for proxypass (read-only)
      # - ${WEB_LOG}:/var/log/nginx # Logs
      # - ${WEB_DATA}:/usr/share/nginx/html # Data
      - ${PYTHON}
